# -*- coding: utf-8 -*-
"""Day26_Exercise_One.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o87f0ZFLtX0OJHINbsWGlFXlmI_vYAi_

**Do the following task:**
1. Load the dataset
2. Clean the text
3. Convert text to features using TF-IDF
4. Train, test a simple multiclass model of your choice to predict resume category
5. Evaluate the result
"""

import re
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import string

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
#Logistic Regression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

#1) Load the dataset
df=pd.read_csv("/content/sample_data/UpdatedResumeDataSet.csv")
df.head(5)

#2) Clean the dataset
def clean_text(text):
  text=str(text)
  text=re.sub(r'http\S+','',text) # Fixed \http\S++ to http\S+
  text=text.translate(str.maketrans('','',string.punctuation))
  text=re.sub(r'\s+',' ',text).strip() # Changed to replace with single space and strip
  text=re.sub(r'[^\x00-\x7F]','',text)
  text=text.lower()
  return text

#Add new column
df['cleaned_resume']=df['Resume'].apply(clean_text)
df

#3,4 and 5
le = LabelEncoder()
df['Category']=le.fit_transform(df['Category'])
X=df['cleaned_resume']
y=df['Category']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42, stratify=y)

#Convert test to feature using TF-IDF
tfidf=TfidfVectorizer(max_features=5000, stop_words='english', sublinear_tf=True)
X_train_tfidf=tfidf.fit_transform(X_train)
X_test_tfidf=tfidf.transform(X_test)

#4. Train and test a simple multiclass model of your choice to predict resume category
model=LogisticRegression()
model.fit(X_train_tfidf,y_train)

y_pred=model.predict(X_test_tfidf)
print("Accuracy: ",accuracy_score(y_test,y_pred))
print("Confusion Matrix: ",confusion_matrix(y_test,y_pred))
print("Classification Report: ",classification_report(y_test,y_pred))

#Take a new resume and predict category